# Generated by Django 2.0.6 on 2018-06-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chart_row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.TextField()),
                ('chart', models.ImageField(blank=True, null=True, upload_to='')),
                ('period', models.CharField(max_length=2)),
                ('dt', models.CharField(max_length=2)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
